import Head from "next/head";
import { useCallback } from "react";
// import Product from "../assets/myProducts";
import Layout from "../components/Layout";
// import MyProducts from "./MyProducts";
import { useRouter } from "next/router";
import {getAllProducts} from "../lib/productSotre";
import {ProductContext} from "../context/ProductContext";
import { useContext } from "react";

export default function Home({products}) {
  const router = useRouter();

  


  const viewProductDetails = useCallback((productId) => {
    router.push(`/product/${productId}`)
  }, [router])

  return (
    <Layout>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="heading1">Yeni Ürünler</h1>

      <main className="main">
        {products.map((product) => {
          return (
            <div className="productcard" onClick={() => viewProductDetails(product.id)} key = {product.id}>
              <img src={product.images[0]} alt="" className="productimage1" />
              <div className="productfeatures">
                <h5 className="productname">{product.name}</h5>
                <p>{product.brand}</p>
                <div className="salesDiv">
                  <h6 className="price">₺{product.price}.00</h6>
                  <h4>₺{product.salePrice}.00</h4>
                </div>
              </div>
            </div>
          );
        })}
      </main>
    </Layout>
  );
};


export const getServerSideProps = async () => {
  const products = await getAllProducts();

  return {
    props : {
      products,
    }
  }
}

